# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Graficas.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys 
from PyQt5 import QtCore, QtGui, QtWidgets
#Para comunicar el arduino
import pyfirmata
import time
import numpy as np 
# graficas  
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt 
#Comprobaciones
print(dir(pyfirmata))
print(dir(sys.builtin_module_names))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 444)
        MainWindow.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 390, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(370, 50, 41, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 60, 47, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(370, 230, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(580, 230, 47, 13))
        self.label_11.setObjectName("label_11")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 60, 231, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.doubleSpinBox_umbral = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_umbral.setObjectName("doubleSpinBox_umbral")
        self.verticalLayout_4.addWidget(self.doubleSpinBox_umbral)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.start = QtWidgets.QPushButton(self.layoutWidget)
        self.start.setObjectName("start")
        self.verticalLayout_6.addWidget(self.start)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lcd_voltaje = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcd_voltaje.setObjectName("lcd_voltaje")
        self.verticalLayout_2.addWidget(self.lcd_voltaje)
        self.lcd_current = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcd_current.setObjectName("lcd_current")
        self.verticalLayout_2.addWidget(self.lcd_current)
        self.lcd_power = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcd_power.setObjectName("lcd_power")
        self.verticalLayout_2.addWidget(self.lcd_power)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.graphicsView_voltage = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_voltage.setGeometry(QtCore.QRect(310, 80, 161, 131))
        self.graphicsView_voltage.setObjectName("graphicsView_voltage")
        self.graphicsView_current = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_current.setGeometry(QtCore.QRect(510, 80, 161, 131))
        self.graphicsView_current.setObjectName("graphicsView_current")
        self.graphicsView_power = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_power.setGeometry(QtCore.QRect(310, 260, 161, 131))
        self.graphicsView_power.setObjectName("graphicsView_power")
        self.graphicsView_energy = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_energy.setGeometry(QtCore.QRect(510, 260, 161, 131))
        self.graphicsView_energy.setObjectName("graphicsView_energy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        print("CONEXION CON ARDUINO")  
        self.start.clicked.connect(self.inicio)
    
    def inicio(self):
        print("Inicio")
        umbral = self.doubleSpinBox_umbral.value()
        print(umbral)
        self.lcd_voltaje.display(umbral)
        self.grafica1 = Canvas_voltage()
        self.ui.graph_voltage.addWidget(self.grafica1)

class Canvas_voltage(FigureCanvas): ## Clase para graficar voltaje
    def __init__(self,parent=None):
        self.fig , self.ax = plt.subplots(1, dpi=100, figsize=(5,5),sharey=True,facecolor='white')
        super()._init__(self.fig)

        self.fig.subtitle('Voltaje', size=9)
        np.random.seed(20)
        y = np.random.randn(150).cumsum()

        self.ax = plt.axes()
        plt.plot(y,color='magenta')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setAccessibleName(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Instrumentación Virtual Aplicada"))
        self.label_7.setText(_translate("MainWindow", "Luis Escárcega Corona"))
        self.label_8.setText(_translate("MainWindow", "Voltaje"))
        self.label_9.setText(_translate("MainWindow", "Corriente"))
        self.label_10.setText(_translate("MainWindow", "Potencia"))
        self.label_11.setText(_translate("MainWindow", "Energía"))
        self.label_4.setText(_translate("MainWindow", "Umbral de energía [W/h]"))
        self.start.setText(_translate("MainWindow", "Iniciar"))
        self.label_3.setText(_translate("MainWindow", "Voltaje"))
        self.label_5.setText(_translate("MainWindow", "Corriente"))
        self.label_6.setText(_translate("MainWindow", "Potencia"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
